### ISSUE TITLE
Mysql Container MYSQL_USER=root error

### ISSUE THREAD

**Issue by kanak** [andres-sacco/manning-twa-api#1]
Hi,

I noticed this error in the logs, which causes the container to fail to start, and an endless loop in docker compose due to `restart: always`:

```
[Entrypoint]: MYSQL_USER="root", MYSQL_USER and MYSQL_PASSWORD are for configuring a regular user and cannot be used for the root user                                                      
    Remove MYSQL_USER="root" and use one of the following to control the root user password:                   
    - MYSQL_ROOT_PASSWORD                                                                                      
    - MYSQL_ALLOW_EMPTY_PASSWORD                                                                               
    - MYSQL_RANDOM_ROOT_PASSWORD   
```

Removing the `MYSQL_USER=root` seems to fix the problem:
* no more errors in logs
* containers not repeatedly restarting
* api-catalog service seems to work fine (tested via one of the postman samples you had).

**Comment by andres-sacco** [comment]
Thanks @kanak for report the issue and the possible solution. I introduce the fix the both docker-compose files.
